# Generated by Django 5.0.6 on 2024-10-21 07:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.gen_ran_code, max_length=8, unique=True),
        ),
    ]
